//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQS.App.MQSKeyServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bokesys.com/MQS/MQSKeyService", ConfigurationName="MQSKeyServices.MQSKeyServiceSoap")]
    public interface MQSKeyServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bokesys.com/MQS/MQSKeyService/GetClientInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DQS.App.MQSKeyServices.ClientKeyInfo[] GetClientInfos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bokesys.com/MQS/MQSKeyService/SubmitClientInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SubmitClientInfo(DQS.App.MQSKeyServices.ClientKeyInfo info);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bokesys.com/MQS/MQSKeyService")]
    public partial class ClientKeyInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string keyHidField;
        
        private string keyVersionField;
        
        private string keyDecryptedContentField;
        
        private string enterpriseNameField;
        
        private string organizationCodeField;
        
        private string industryField;
        
        private string enterpriseTypeField;
        
        private string enterpriseLevelField;
        
        private int employeeCountField;
        
        private string enterpriseMailField;
        
        private string enterpriseWebsiteField;
        
        private string enterpriseAddressField;
        
        private string enterprisePostCodeField;
        
        private string enterprisePhoneField;
        
        private string enterpriseFaxField;
        
        private string contactPersonField;
        
        private string contactPhoneField;
        
        private string registerAddressField;
        
        private System.Nullable<System.DateTime> registerDateField;
        
        private string registerLicenseNoField;
        
        private string registerTaxNoField;
        
        private System.Nullable<System.DateTime> licenseValidateDateField;
        
        private System.Nullable<System.DateTime> tradeLicenseValidateDateField;
        
        private string clientMacAddressField;
        
        private System.DateTime installDateField;
        
        private System.DateTime infoSendDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KeyHid {
            get {
                return this.keyHidField;
            }
            set {
                this.keyHidField = value;
                this.RaisePropertyChanged("KeyHid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KeyVersion {
            get {
                return this.keyVersionField;
            }
            set {
                this.keyVersionField = value;
                this.RaisePropertyChanged("KeyVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KeyDecryptedContent {
            get {
                return this.keyDecryptedContentField;
            }
            set {
                this.keyDecryptedContentField = value;
                this.RaisePropertyChanged("KeyDecryptedContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EnterpriseName {
            get {
                return this.enterpriseNameField;
            }
            set {
                this.enterpriseNameField = value;
                this.RaisePropertyChanged("EnterpriseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OrganizationCode {
            get {
                return this.organizationCodeField;
            }
            set {
                this.organizationCodeField = value;
                this.RaisePropertyChanged("OrganizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Industry {
            get {
                return this.industryField;
            }
            set {
                this.industryField = value;
                this.RaisePropertyChanged("Industry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EnterpriseType {
            get {
                return this.enterpriseTypeField;
            }
            set {
                this.enterpriseTypeField = value;
                this.RaisePropertyChanged("EnterpriseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EnterpriseLevel {
            get {
                return this.enterpriseLevelField;
            }
            set {
                this.enterpriseLevelField = value;
                this.RaisePropertyChanged("EnterpriseLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int EmployeeCount {
            get {
                return this.employeeCountField;
            }
            set {
                this.employeeCountField = value;
                this.RaisePropertyChanged("EmployeeCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string EnterpriseMail {
            get {
                return this.enterpriseMailField;
            }
            set {
                this.enterpriseMailField = value;
                this.RaisePropertyChanged("EnterpriseMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EnterpriseWebsite {
            get {
                return this.enterpriseWebsiteField;
            }
            set {
                this.enterpriseWebsiteField = value;
                this.RaisePropertyChanged("EnterpriseWebsite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string EnterpriseAddress {
            get {
                return this.enterpriseAddressField;
            }
            set {
                this.enterpriseAddressField = value;
                this.RaisePropertyChanged("EnterpriseAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string EnterprisePostCode {
            get {
                return this.enterprisePostCodeField;
            }
            set {
                this.enterprisePostCodeField = value;
                this.RaisePropertyChanged("EnterprisePostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string EnterprisePhone {
            get {
                return this.enterprisePhoneField;
            }
            set {
                this.enterprisePhoneField = value;
                this.RaisePropertyChanged("EnterprisePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string EnterpriseFax {
            get {
                return this.enterpriseFaxField;
            }
            set {
                this.enterpriseFaxField = value;
                this.RaisePropertyChanged("EnterpriseFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ContactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
                this.RaisePropertyChanged("ContactPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ContactPhone {
            get {
                return this.contactPhoneField;
            }
            set {
                this.contactPhoneField = value;
                this.RaisePropertyChanged("ContactPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string RegisterAddress {
            get {
                return this.registerAddressField;
            }
            set {
                this.registerAddressField = value;
                this.RaisePropertyChanged("RegisterAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<System.DateTime> RegisterDate {
            get {
                return this.registerDateField;
            }
            set {
                this.registerDateField = value;
                this.RaisePropertyChanged("RegisterDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string RegisterLicenseNo {
            get {
                return this.registerLicenseNoField;
            }
            set {
                this.registerLicenseNoField = value;
                this.RaisePropertyChanged("RegisterLicenseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string RegisterTaxNo {
            get {
                return this.registerTaxNoField;
            }
            set {
                this.registerTaxNoField = value;
                this.RaisePropertyChanged("RegisterTaxNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<System.DateTime> LicenseValidateDate {
            get {
                return this.licenseValidateDateField;
            }
            set {
                this.licenseValidateDateField = value;
                this.RaisePropertyChanged("LicenseValidateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<System.DateTime> TradeLicenseValidateDate {
            get {
                return this.tradeLicenseValidateDateField;
            }
            set {
                this.tradeLicenseValidateDateField = value;
                this.RaisePropertyChanged("TradeLicenseValidateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
                this.RaisePropertyChanged("ClientMacAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public System.DateTime InstallDate {
            get {
                return this.installDateField;
            }
            set {
                this.installDateField = value;
                this.RaisePropertyChanged("InstallDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public System.DateTime InfoSendDate {
            get {
                return this.infoSendDateField;
            }
            set {
                this.infoSendDateField = value;
                this.RaisePropertyChanged("InfoSendDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MQSKeyServiceSoapChannel : DQS.App.MQSKeyServices.MQSKeyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MQSKeyServiceSoapClient : System.ServiceModel.ClientBase<DQS.App.MQSKeyServices.MQSKeyServiceSoap>, DQS.App.MQSKeyServices.MQSKeyServiceSoap {
        
        public MQSKeyServiceSoapClient() {
        }
        
        public MQSKeyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MQSKeyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MQSKeyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MQSKeyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DQS.App.MQSKeyServices.ClientKeyInfo[] GetClientInfos() {
            return base.Channel.GetClientInfos();
        }
        
        public bool SubmitClientInfo(DQS.App.MQSKeyServices.ClientKeyInfo info) {
            return base.Channel.SubmitClientInfo(info);
        }
    }
}
