//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Table {
    
    private TableColumn[] storedataitemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Column", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TableColumn[] Items {
        get {
            return this.storedataitemsField;
        }
        set {
            this.storedataitemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TableColumn {
    
    private string eRP_RECEIVE_IDField;
    
    private string oRDER_ITEM_IDField;
    
    private string pRODUCT_IDField;
    
    private string qUANTITYField;
    
    private string bATCH_NOField;
    
    private string vALID_DATEField;
    
    private string oRG_IDField;
    
    private string pROOF_IDField;
    
    private string pROOF_DATEField;
    
    private string gOODS_AMOUNTField;
    
    private string oRD_ORDER_IDField;
    
    private string uP_PATITIONField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ERP_RECEIVE_ID {
        get {
            return this.eRP_RECEIVE_IDField;
        }
        set {
            this.eRP_RECEIVE_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_ITEM_ID {
        get {
            return this.oRDER_ITEM_IDField;
        }
        set {
            this.oRDER_ITEM_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PRODUCT_ID {
        get {
            return this.pRODUCT_IDField;
        }
        set {
            this.pRODUCT_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string QUANTITY {
        get {
            return this.qUANTITYField;
        }
        set {
            this.qUANTITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BATCH_NO {
        get {
            return this.bATCH_NOField;
        }
        set {
            this.bATCH_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VALID_DATE {
        get {
            return this.vALID_DATEField;
        }
        set {
            this.vALID_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORG_ID {
        get {
            return this.oRG_IDField;
        }
        set {
            this.oRG_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PROOF_ID {
        get {
            return this.pROOF_IDField;
        }
        set {
            this.pROOF_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PROOF_DATE {
        get {
            return this.pROOF_DATEField;
        }
        set {
            this.pROOF_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GOODS_AMOUNT {
        get {
            return this.gOODS_AMOUNTField;
        }
        set {
            this.gOODS_AMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORD_ORDER_ID {
        get {
            return this.oRD_ORDER_IDField;
        }
        set {
            this.oRD_ORDER_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UP_PATITION {
        get {
            return this.uP_PATITIONField;
        }
        set {
            this.uP_PATITIONField = value;
        }
    }
}
