//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQS.AppViews.Operation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSaveAndOutStoreButtonVisible {
            get {
                return ((bool)(this["IsSaveAndOutStoreButtonVisible"]));
            }
            set {
                this["IsSaveAndOutStoreButtonVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowNoCodeStoreIn {
            get {
                return ((bool)(this["AllowNoCodeStoreIn"]));
            }
            set {
                this["AllowNoCodeStoreIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowNoCodeStoreOut {
            get {
                return ((bool)(this["AllowNoCodeStoreOut"]));
            }
            set {
                this["AllowNoCodeStoreOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingBusinessPersonISNULL {
            get {
                return ((bool)(this["SettingBusinessPersonISNULL"]));
            }
            set {
                this["SettingBusinessPersonISNULL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JudgementSaleBillPrice {
            get {
                return ((bool)(this["JudgementSaleBillPrice"]));
            }
            set {
                this["JudgementSaleBillPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseDepartment {
            get {
                return ((bool)(this["IsUseDepartment"]));
            }
            set {
                this["IsUseDepartment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsBillCategory {
            get {
                return ((bool)(this["IsBillCategory"]));
            }
            set {
                this["IsBillCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsControlProductForDealer {
            get {
                return ((bool)(this["IsControlProductForDealer"]));
            }
            set {
                this["IsControlProductForDealer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCanPurchaseBackUnStore {
            get {
                return ((bool)(this["IsCanPurchaseBackUnStore"]));
            }
            set {
                this["IsCanPurchaseBackUnStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowNoCodeStoreBackIn {
            get {
                return ((bool)(this["AllowNoCodeStoreBackIn"]));
            }
            set {
                this["AllowNoCodeStoreBackIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowNoCodeStoreBackOut {
            get {
                return ((bool)(this["AllowNoCodeStoreBackOut"]));
            }
            set {
                this["AllowNoCodeStoreBackOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingBusinessPersonWithDealer {
            get {
                return ((bool)(this["SettingBusinessPersonWithDealer"]));
            }
            set {
                this["SettingBusinessPersonWithDealer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRestriction {
            get {
                return ((bool)(this["IsRestriction"]));
            }
            set {
                this["IsRestriction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EqSaleBillPrice {
            get {
                return ((bool)(this["EqSaleBillPrice"]));
            }
            set {
                this["EqSaleBillPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsEmptySaleManSaveBill {
            get {
                return ((bool)(this["IsEmptySaleManSaveBill"]));
            }
            set {
                this["IsEmptySaleManSaveBill"] = value;
            }
        }
    }
}
