//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="Table", IsNullable=false)]
public partial class OrderTable {

    private OrderTableColumn[] columnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Column")]
    public OrderTableColumn[] Column
    {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class OrderTableColumn
{
    
    private string rECORDIDField;
    
    private string oRDER_IDField;
    
    private string oRDERCODEField;
    
    private string bUYERORGIDField;
    
    private string bUYERNAMEField;
    
    private string bUYEREASYField;
    
    private string mEDICALNAMEField;
    
    private string pRODUCTIDField;
    
    private string pRODUCTNAMEField;
    
    private string mEDICALMODEField;
    
    private string mEDICALSPECField;
    
    private string mETRICNAMEField;
    
    private string fATORYIDField;
    
    private string fACTORYNAMEField;
    
    private byte rEQUESTQTYField;
    
    private decimal pRICEField;
    
    private string cREATEDATEField;
    
    private byte dEGREEField;
    
    private string oRDERREMARKField;
    
    private string rEMARKField;
    
    private string wAREHOUSENAMEField;
    
    private string cOMPANY_IDField;
    
    private string dEPART_NAMEField;
    
    /// <remarks/>
    public string RECORDID {
        get {
            return this.rECORDIDField;
        }
        set {
            this.rECORDIDField = value;
        }
    }
    
    /// <remarks/>
    public string ORDER_ID {
        get {
            return this.oRDER_IDField;
        }
        set {
            this.oRDER_IDField = value;
        }
    }
    
    /// <remarks/>
    public string ORDERCODE {
        get {
            return this.oRDERCODEField;
        }
        set {
            this.oRDERCODEField = value;
        }
    }
    
    /// <remarks/>
    public string BUYERORGID {
        get {
            return this.bUYERORGIDField;
        }
        set {
            this.bUYERORGIDField = value;
        }
    }
    
    /// <remarks/>
    public string BUYERNAME {
        get {
            return this.bUYERNAMEField;
        }
        set {
            this.bUYERNAMEField = value;
        }
    }
    
    /// <remarks/>
    public string BUYEREASY {
        get {
            return this.bUYEREASYField;
        }
        set {
            this.bUYEREASYField = value;
        }
    }
    
    /// <remarks/>
    public string MEDICALNAME {
        get {
            return this.mEDICALNAMEField;
        }
        set {
            this.mEDICALNAMEField = value;
        }
    }
    
    /// <remarks/>
    public string PRODUCTID {
        get {
            return this.pRODUCTIDField;
        }
        set {
            this.pRODUCTIDField = value;
        }
    }
    
    /// <remarks/>
    public string PRODUCTNAME {
        get {
            return this.pRODUCTNAMEField;
        }
        set {
            this.pRODUCTNAMEField = value;
        }
    }
    
    /// <remarks/>
    public string MEDICALMODE {
        get {
            return this.mEDICALMODEField;
        }
        set {
            this.mEDICALMODEField = value;
        }
    }
    
    /// <remarks/>
    public string MEDICALSPEC {
        get {
            return this.mEDICALSPECField;
        }
        set {
            this.mEDICALSPECField = value;
        }
    }
    
    /// <remarks/>
    public string METRICNAME {
        get {
            return this.mETRICNAMEField;
        }
        set {
            this.mETRICNAMEField = value;
        }
    }
    
    /// <remarks/>
    public string FATORYID {
        get {
            return this.fATORYIDField;
        }
        set {
            this.fATORYIDField = value;
        }
    }
    
    /// <remarks/>
    public string FACTORYNAME {
        get {
            return this.fACTORYNAMEField;
        }
        set {
            this.fACTORYNAMEField = value;
        }
    }
    
    /// <remarks/>
    public byte REQUESTQTY {
        get {
            return this.rEQUESTQTYField;
        }
        set {
            this.rEQUESTQTYField = value;
        }
    }
    
    /// <remarks/>
    public decimal PRICE {
        get {
            return this.pRICEField;
        }
        set {
            this.pRICEField = value;
        }
    }
    
    /// <remarks/>
    public string CREATEDATE {
        get {
            return this.cREATEDATEField;
        }
        set {
            this.cREATEDATEField = value;
        }
    }
    
    /// <remarks/>
    public byte DEGREE {
        get {
            return this.dEGREEField;
        }
        set {
            this.dEGREEField = value;
        }
    }
    
    /// <remarks/>
    public string ORDERREMARK {
        get {
            return this.oRDERREMARKField;
        }
        set {
            this.oRDERREMARKField = value;
        }
    }
    
    /// <remarks/>
    public string REMARK {
        get {
            return this.rEMARKField;
        }
        set {
            this.rEMARKField = value;
        }
    }
    
    /// <remarks/>
    public string WAREHOUSENAME {
        get {
            return this.wAREHOUSENAMEField;
        }
        set {
            this.wAREHOUSENAMEField = value;
        }
    }
    
    /// <remarks/>
    public string COMPANY_ID {
        get {
            return this.cOMPANY_IDField;
        }
        set {
            this.cOMPANY_IDField = value;
        }
    }
    
    /// <remarks/>
    public string DEPART_NAME {
        get {
            return this.dEPART_NAMEField;
        }
        set {
            this.dEPART_NAMEField = value;
        }
    }
}
