//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="Table", IsNullable=false)]
public partial class StoreOutTable {
    
    private StoreOutTableColumn[] columnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Column")]
    public StoreOutTableColumn[] Column
    {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StoreOutTableColumn
{
    
    private ulong eRP_RECEIVE_IDField;
    
    private ulong oRDER_ITEM_IDField;
    
    private byte pRODUCT_IDField;
    
    private byte qUANTITYField;
    
    private ushort bATCH_NOField;
    
    private string vALID_DATEField;
    
    private string oRG_IDField;
    
    private byte pROOF_IDField;
    
    private string pROOF_DATEField;
    
    private byte gOODS_AMOUNTField;
    
    private string oRD_ORDER_IDField;
    
    private ushort uP_PATITIONField;
    
    /// <remarks/>
    public ulong ERP_RECEIVE_ID {
        get {
            return this.eRP_RECEIVE_IDField;
        }
        set {
            this.eRP_RECEIVE_IDField = value;
        }
    }
    
    /// <remarks/>
    public ulong ORDER_ITEM_ID {
        get {
            return this.oRDER_ITEM_IDField;
        }
        set {
            this.oRDER_ITEM_IDField = value;
        }
    }
    
    /// <remarks/>
    public byte PRODUCT_ID {
        get {
            return this.pRODUCT_IDField;
        }
        set {
            this.pRODUCT_IDField = value;
        }
    }
    
    /// <remarks/>
    public byte QUANTITY {
        get {
            return this.qUANTITYField;
        }
        set {
            this.qUANTITYField = value;
        }
    }
    
    /// <remarks/>
    public ushort BATCH_NO {
        get {
            return this.bATCH_NOField;
        }
        set {
            this.bATCH_NOField = value;
        }
    }
    
    /// <remarks/>
    public string VALID_DATE {
        get {
            return this.vALID_DATEField;
        }
        set {
            this.vALID_DATEField = value;
        }
    }
    
    /// <remarks/>
    public string ORG_ID {
        get {
            return this.oRG_IDField;
        }
        set {
            this.oRG_IDField = value;
        }
    }
    
    /// <remarks/>
    public byte PROOF_ID {
        get {
            return this.pROOF_IDField;
        }
        set {
            this.pROOF_IDField = value;
        }
    }
    
    /// <remarks/>
    public string PROOF_DATE {
        get {
            return this.pROOF_DATEField;
        }
        set {
            this.pROOF_DATEField = value;
        }
    }
    
    /// <remarks/>
    public byte GOODS_AMOUNT {
        get {
            return this.gOODS_AMOUNTField;
        }
        set {
            this.gOODS_AMOUNTField = value;
        }
    }
    
    /// <remarks/>
    public string ORD_ORDER_ID {
        get {
            return this.oRD_ORDER_IDField;
        }
        set {
            this.oRD_ORDER_IDField = value;
        }
    }
    
    /// <remarks/>
    public ushort UP_PATITION {
        get {
            return this.uP_PATITIONField;
        }
        set {
            this.uP_PATITIONField = value;
        }
    }
}
